package com.armsx2.config

import android.content.Context
import com.armsx2.core.Ps1Config
import java.io.File
import java.util.Locale

/**
 * Reads and writes the native `settings.toml` that `frontend/config.c` consumes.
 *
 * Writing generates the FULL file from a [Ps1Settings] (the native parser reads every key
 * defensively and ignores unknown ones, so a complete regenerate is safe). The required top-level
 * `psxe_version` is emitted as "latest" to match the native default — the core only checks that the
 * key is present, not its value. Reading is a small section-aware TOML scan good enough for the flat
 * key/value/bool/int/array shapes this file uses; anything unparseable falls back to the default.
 *
 * As of the per-game work this class also owns the LAYERING: `defaults < global < per-game`,
 * resolved in [load] and nowhere else, with `settings.toml` regenerated from the winning merge by
 * [render]. See the layer comment at the top of the object.
 */
object Ps1SettingsStore {

    // ---- layers ---------------------------------------------------------------------------
    //
    // THREE layers, resolved in exactly one place ([load]):
    //
    //     defaults  <  global  <  per-game
    //
    //   defaults  — Ps1Settings()'s field defaults, which [parse] starts from.
    //   global    — `settings.global.toml`, the user's baseline. Authored ONLY by [saveGlobal].
    //   per-game  — the sparse key set in [Ps1GameSettings], applied over the global TEXT.
    //
    // `settings.toml` — the file frontend/config.c reads — is the RENDER TARGET, regenerated by
    // [render] from whichever scope is active. There is deliberately NO second file the core
    // layers: the core reads one file and the merge happens here, in Kotlin. (The sibling PS2
    // project layered a per-game INI underneath its own JSON store and spent years fielding
    // "this setting does nothing" reports caused by the lower layer invisibly winning.)

    /** The global baseline. Seeded verbatim from the user's existing `settings.toml` — see [globalText]. */
    private fun globalFile(context: Context): File = File(context.filesDir, "settings.global.toml")

    /**
     * The global layer's raw text, seeding it from the user's existing `settings.toml` on first use.
     *
     * MIGRATION: before this file existed, `settings.toml` WAS the global layer. The seed is a
     * verbatim copy — comments, unknown keys and core-written keys included — and `settings.toml`
     * itself is left exactly as it is. An install with no per-game overrides therefore renders a
     * byte-identical `settings.toml`, which is the whole migration requirement: absence of overrides
     * has to behave exactly like before.
     */
    private fun globalText(context: Context): String {
        val g = globalFile(context)
        if (g.isFile) return runCatching { g.readText() }.getOrDefault("")
        val legacy = Ps1Config.settingsFile(context)
        val seed = runCatching { if (legacy.isFile) legacy.readText() else "" }.getOrDefault("")
        if (seed.isNotEmpty()) {
            runCatching {
                g.parentFile?.mkdirs()
                g.writeText(seed)
            }
        }
        return seed
    }

    /**
     * The game whose layer `settings.toml` currently reflects, or null for plain global.
     *
     * Set by the launcher immediately before the core boots and cleared when the session ends, so
     * every later write ([saveGlobal], [update]) re-renders for the game that is actually running
     * rather than silently reverting it to global mid-session.
     */
    @Volatile
    var activeGameKey: String? = null
        private set

    /** Point the rendered `settings.toml` at [gameKey] (null = global) and regenerate it now. */
    fun setActiveGame(context: Context, gameKey: String?) {
        val eff = gameKey?.takeIf { it.isNotBlank() }
        activeGameKey = eff
        runCatching { render(context) }
    }

    /**
     * ★ THE merge point. Every resolved [Ps1Settings] in the app comes from here.
     *
     * [gameKey] null resolves `defaults < global`; non-null resolves `defaults < global < per-game`.
     * The merge is done in `settings.toml` KEY space — the per-game keys are overlaid onto the
     * global file's text and the result is parsed — so a field added to [Ps1Settings] participates
     * the moment it has a [serialize] line, with no per-field list anywhere to go stale.
     */
    fun load(context: Context, gameKey: String? = null): Ps1Settings {
        val base = globalText(context)
        val overrides = if (gameKey == null) emptyMap() else Ps1GameSettings.overridesFor(gameKey)
        return try {
            parse(if (overrides.isEmpty()) base else overlay(base, overrides))
        } catch (_: Exception) {
            Ps1Settings()
        }
    }

    /** The settings the CORE is running with right now — global, or the active game's merge. */
    fun active(context: Context): Ps1Settings = load(context, activeGameKey)

    /** Write the GLOBAL layer. Unchanged meaning for every existing caller. */
    fun save(context: Context, s: Ps1Settings) = saveGlobal(context, s)

    private fun saveGlobal(context: Context, s: Ps1Settings) {
        val g = globalFile(context)
        val existing = globalText(context)
        runCatching {
            g.parentFile?.mkdirs()
            g.writeText(preserveUnknown(serialize(s), existing))
        }
        render(context)
    }

    /**
     * Apply an edit at [gameKey]'s tier and persist it.
     *
     * null [gameKey] rewrites the global layer. A non-null one records ONLY the keys this single
     * edit actually changed as per-game overrides — the sparse contract — by diffing the serialized
     * form before and after. That diff is why a field nobody here knows about still works: if it
     * has a serialize line it shows up in the diff, and if it does not it could never have been
     * persisted at all, globally or otherwise.
     *
     * Returns the resolved settings after the edit.
     */
    fun update(
        context: Context,
        gameKey: String?,
        transform: (Ps1Settings) -> Ps1Settings,
    ): Ps1Settings {
        val base = load(context, gameKey)
        val next = transform(base)
        if (gameKey == null) {
            saveGlobal(context, next)
        } else {
            Ps1GameSettings.putOverrides(gameKey, changedKeys(base, next))
            render(context)
        }
        return next
    }

    /** Drop [tomlKeys] from [gameKey] so they follow the global layer again, and re-render. */
    fun clearOverrides(context: Context, gameKey: String?, tomlKeys: Collection<String>) {
        Ps1GameSettings.clearOverrides(gameKey, tomlKeys)
        render(context)
    }

    /** Drop EVERY override for [gameKey], and re-render. */
    fun clearAllOverrides(context: Context, gameKey: String?) {
        Ps1GameSettings.clearAll(gameKey)
        render(context)
    }

    /**
     * Regenerate `settings.toml` for [activeGameKey].
     *
     * This is the ONLY writer of that file on the Kotlin side. Everything else edits a layer and
     * lets this rebuild the core's view of it.
     */
    fun render(context: Context) {
        val merged = load(context, activeGameKey)
        val file = Ps1Config.settingsFile(context)
        val existing = runCatching { if (file.isFile) file.readText() else "" }.getOrDefault("")
        runCatching {
            file.parentFile?.mkdirs()
            file.writeText(preserveUnknown(serialize(merged), existing))
        }
    }

    // ---- key space ------------------------------------------------------------------------

    /**
     * Every `"section.key"` the CURRENT build emits, derived from [serialize] rather than listed.
     *
     * Adding a field to [Ps1Settings] + a line to [serialize] is all it takes to make it
     * overridable; forgetting one is already fatal for the GLOBAL layer too (the key would be
     * dropped from settings.toml on the first save), so there is no per-game-only way to get this
     * wrong.
     */
    val ALL_KEYS: Set<String> by lazy { keyValues(serialize(Ps1Settings())).keys }

    /**
     * The subset a game may override.
     *
     * `[library]` is excluded — the ROM folder list is a property of the installation, not of a
     * disc, and a game that pinned it would quietly break library scanning for itself. So is the
     * file-level `psxe_version` marker (no section, hence no dot).
     */
    val PER_GAME_KEYS: Set<String> by lazy {
        ALL_KEYS.filterTo(HashSet()) { it.contains('.') && !it.startsWith("library.") }
    }

    /** Section of a `"section.key"`, or "" for a top-level key. */
    fun sectionOf(tomlKey: String): String = tomlKey.substringBeforeLast('.', "")

    /** The GLOBAL value of [tomlKey] as it would be written, for "…instead of X" copy. */
    fun globalValueOf(context: Context, tomlKey: String): String? =
        keyValues(serialize(load(context, null)))[tomlKey]

    /** Flat `"section.key"` -> raw value text for a generated/complete TOML body. */
    private fun keyValues(text: String): LinkedHashMap<String, String> {
        val out = LinkedHashMap<String, String>()
        var section = ""
        for (raw in text.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.substring(1, line.length - 1).trim(); continue
            }
            val eq = line.indexOf('=')
            if (eq <= 0) continue
            val key = line.substring(0, eq).trim()
            out[if (section.isEmpty()) key else "$section.$key"] = line.substring(eq + 1).trim()
        }
        return out
    }

    /** Keys whose serialized value differs between [base] and [next], restricted to [PER_GAME_KEYS]. */
    private fun changedKeys(base: Ps1Settings, next: Ps1Settings): Map<String, String> {
        val before = keyValues(serialize(base))
        val after = keyValues(serialize(next))
        val out = LinkedHashMap<String, String>()
        for ((k, v) in after) if (k in PER_GAME_KEYS && before[k] != v) out[k] = v
        return out
    }

    /**
     * Overlay per-game [overrides] onto the global file's [base] text.
     *
     * Replaces the value in place where the key already exists (so indentation and any trailing
     * comment layout survive), and APPENDS into the right section where it does not — necessary
     * because an older global file simply will not contain a key added in a later build.
     *
     * Only keys in [PER_GAME_KEYS] are applied. That is what makes a REMOVED or RENAMED setting
     * safe: its stored override becomes inert instead of being injected back into settings.toml as
     * a resurrected key, and it is still on disk (and listed in the settings UI) if it returns.
     */
    private fun overlay(base: String, overrides: Map<String, String>): String {
        val remaining = LinkedHashMap(overrides.filterKeys { it in PER_GAME_KEYS })
        if (remaining.isEmpty()) return base

        val out = StringBuilder()
        fun drain(section: String) {
            val it = remaining.entries.iterator()
            while (it.hasNext()) {
                val e = it.next()
                if (sectionOf(e.key) != section) continue
                out.append("    ").append(e.key.substringAfterLast('.'))
                    .append(" = ").append(e.value).append('\n')
                it.remove()
            }
        }

        var section = ""
        for (raw in base.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.startsWith("[") && line.endsWith("]")) {
                // Anything still unplaced for the section we are LEAVING goes in before the
                // next header, or it would land in the wrong table.
                drain(section)
                section = line.substring(1, line.length - 1).trim()
                out.append(raw).append('\n')
                continue
            }
            val eq = line.indexOf('=')
            if (eq > 0) {
                val key = line.substring(0, eq).trim()
                val full = if (section.isEmpty()) key else "$section.$key"
                val replacement = remaining.remove(full)
                if (replacement != null) {
                    out.append(raw.takeWhile { it == ' ' || it == '\t' })
                        .append(key).append(" = ").append(replacement).append('\n')
                    continue
                }
            }
            out.append(raw).append('\n')
        }
        drain(section)

        // Sections the global file does not have at all (an old file, a new table).
        remaining.entries.groupBy { sectionOf(it.key) }.forEach { (sec, entries) ->
            if (sec.isNotEmpty()) out.append('[').append(sec).append("]\n")
            entries.forEach {
                out.append("    ").append(it.key.substringAfterLast('.'))
                    .append(" = ").append(it.value).append('\n')
            }
        }
        return out.toString()
    }

    /**
     * Merge any key the CURRENT file has that our generated output does not, back into the
     * matching section.
     *
     * [serialize] rebuilds the file from an explicit key list, so historically any key this
     * class did not know about was erased the next time anything saved. That is not a
     * hypothetical: it silently ate `renderer`, `internal_scale`, `accurate_mask_bit`,
     * `accurate_dither` and `display_aspect_custom` — each of which then read as "the setting
     * does nothing", because it worked until the first save and then reverted.
     *
     * It also erased keys written by the CORE. `SaveSettings()` in frontend/main.cpp writes the
     * same file, and a POSIX-library sync calls straight through here (Ps1Folders.syncFromLibrary
     * → persist → save), so a core-written key could vanish on startup with no user action at
     * all. That is what made settings pushed before launch fail to reach the core.
     *
     * Unknown keys are copied verbatim, so formatting and any trailing comment survive.
     */
    private fun preserveUnknown(generated: String, existing: String): String {
        if (existing.isBlank()) return generated

        // section -> keys we are already emitting
        val known = HashMap<String, MutableSet<String>>()
        var section = ""
        for (raw in generated.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.substring(1, line.length - 1).trim(); continue
            }
            val eq = line.indexOf('=')
            if (eq > 0) known.getOrPut(section) { HashSet() }.add(line.substring(0, eq).trim())
        }

        // section -> original lines for keys we are NOT emitting
        val extra = LinkedHashMap<String, MutableList<String>>()
        section = ""
        for (raw in existing.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.substring(1, line.length - 1).trim(); continue
            }
            val eq = line.indexOf('=')
            if (eq <= 0) continue
            val key = line.substring(0, eq).trim()
            if (known[section]?.contains(key) == true) continue
            extra.getOrPut(section) { ArrayList() }.add(raw.trimEnd())
        }
        if (extra.isEmpty()) return generated

        // Re-emit, appending each section's unknown keys just before the section ends.
        val out = StringBuilder()
        var current = ""
        fun flush() {
            extra.remove(current)?.forEach { out.append(it).append('\n') }
        }
        for (raw in generated.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.startsWith("[") && line.endsWith("]")) {
                flush()
                current = line.substring(1, line.length - 1).trim()
            }
            out.append(raw).append('\n')
        }
        flush()
        // Whole sections the generator has no concept of (a future core adding one).
        extra.forEach { (name, lines) ->
            if (name.isNotEmpty()) out.append('\n').append('[').append(name).append(']').append('\n')
            lines.forEach { out.append(it).append('\n') }
        }
        return out.toString()
    }

    // ---- serialize ----

    private fun serialize(s: Ps1Settings): String = buildString {
        appendLine("# Settings file generated by ARMSX")
        appendLine()
        appendLine("# Don't change please, reserved for future use")
        appendLine("psxe_version = \"latest\"")
        appendLine()
        appendLine("[bios]")
        appendLine("    search_path     = ${str(s.biosSearchPath)}")
        appendLine("    preferred_model = ${str(s.preferredModel)}")
        appendLine("    override_file   = ${str(s.biosOverrideFile)}")
        appendLine()
        appendLine("[console]")
        appendLine("    region          = ${str(s.region)}")
        appendLine()
        appendLine("[cpu]")
        appendLine("    execution_mode  = ${str(s.cpuEngine)}")
        appendLine("    fast_boot       = ${s.fastBoot}")
        appendLine()
        appendLine("[runtime]")
        appendLine("    display_scale = ${s.displayScale}")
        appendLine("    logging_enabled = ${s.loggingEnabled}")
        appendLine("    log_level = ${s.logLevel}")
        appendLine("    quiet = ${s.quiet}")
        appendLine("    frame_limit = ${s.frameLimit}")
        appendLine("    speed_percent = ${s.speedPercent}")
        appendLine("    fps_limit = ${s.fpsLimit}")
        // Always with a decimal point, matching SaveSettings() on the native side — the reader
        // takes a bare integer too, but the two writers of this file should agree on one shape.
        appendLine("    fast_forward_speed = ${String.format(Locale.US, "%.2f", s.fastForwardSpeed)}")
        // MUST be written. This block rewrites [runtime] wholesale from an explicit key list, so
        // a native key with no line here is dropped from settings.toml the first time anything
        // saves — the setting appears to work and then silently reverts. Five settings have been
        // lost on this project exactly that way.
        appendLine("    frame_skip = ${s.frameSkip}")
        appendLine()
        appendLine("[audio]")
        appendLine("    volume = ${s.audioVolume}")
        appendLine("    fast_forward_volume = ${s.audioFastForwardVolume}")
        appendLine("    muted = ${s.audioMuted}")
        appendLine("    mute_fast_forward = ${s.audioMuteFastForward}")
        appendLine("    swap_channels = ${s.audioSwapChannels}")
        appendLine("    skip_reverb = ${s.audioSkipReverb}")
        appendLine("    buffer_ms = ${s.audioBufferMs}")
        appendLine("    driver = ${str(s.audioDriver)}")
        appendLine("    background_playback = ${s.audioBackgroundPlayback}")
        appendLine()
        appendLine("[paths]")
        appendLine("    expansion_rom = ${str(s.expansionRom)}")
        appendLine("    default_psx_exe = ${str(s.defaultPsxExe)}")
        appendLine()
        appendLine("[video]")
        appendLine("    vsync = ${s.vsync}")
        appendLine("    gpu_backend = ${str(s.gpuBackend)}")
        appendLine("    texture_scale_mode = ${s.textureScaleMode}")
        appendLine("    debug_panel = ${s.debugPanel}")
        appendLine("    stretch_mode = ${s.stretchMode}")
        appendLine("    display_aspect = ${str(s.displayAspect)}")
        appendLine("    display_aspect_custom = ${String.format(Locale.US, "%.4f", s.displayAspectCustom)}")
        appendLine("    integer_scaling = ${s.integerScaling}")
        appendLine("    wide_upscale = ${str(s.wideUpscale)}")
        // These two MUST be written. This block rewrites [video] wholesale from an explicit key
        // list, so any key missing here is dropped from settings.toml the first time the user
        // saves anything — the setting would appear to work, then silently revert.
        appendLine("    renderer = ${str(if (s.hwRasterizer) "hardware" else "software")}")
        appendLine("    internal_scale = ${s.internalScale}")
        appendLine("    pgxp = ${s.pgxp}")
        appendLine("    accurate_mask_bit = ${s.accurateMaskBit}")
        appendLine("    accurate_dither = ${s.accurateDither}")
        // Display / video feature set. These MUST be written for the same reason as the two
        // above: [video] is regenerated from this explicit list, so a key with no line here is
        // erased from settings.toml the first time anything saves and the setting silently
        // reverts to its default on the next launch.
        appendLine("    widescreen_hack = ${s.widescreenHack}")
        appendLine("    texture_filter = ${str(s.textureFilter)}")
        appendLine("    downsample = ${s.downsample}")
        appendLine("    deinterlace = ${str(s.deinterlace)}")
        appendLine("    overscan_crop = ${str(s.overscanCrop)}")
        appendLine("    display_rotation = ${s.displayRotation}")
        appendLine("    line_detect = ${str(s.lineDetect)}")
        // Texture dumping / replacement (psx/texrep.h). Same rule as everything above: a key
        // with no line here is erased from settings.toml on the first save.
        appendLine("    texture_dump = ${s.textureDump}")
        appendLine("    texture_replacements = ${s.textureReplacements}")
        appendLine("    texture_dir = ${str(s.textureDir)}")
        appendLine()
        appendLine("[input]")
        appendLine("    analog_mode_default = ${s.analogModeDefault}")
        appendLine("    multitap = ${s.multitap}")
        appendLine()
        appendLine("[emulation]")
        // MUST be written, like every other key in this file: serialize() rebuilds each
        // section from an explicit list, so a native key with no line here is dropped from
        // settings.toml the first time anything saves — the setting appears to work and then
        // silently reverts on the next launch.
        appendLine("    rewind = ${s.rewind}")
        appendLine("    rewind_seconds = ${s.rewindSeconds}")
        appendLine("    rewind_frequency = ${s.rewindFrequency}")
        appendLine("    runahead = ${s.runahead}")
        appendLine()
        // [cheats]. MUST be written, like every other key in this file: serialize() rebuilds
        // each section from an explicit list, so a native key with no line here is dropped
        // from settings.toml the first time anything saves. `enabled_codes` is the user's
        // cheat SELECTION, so losing it would look exactly like "my cheats turned themselves
        // off". frontend/main.cpp writes the same three keys in SaveSettings().
        appendLine("[cheats]")
        appendLine("    enabled = ${s.cheatsEnabled}")
        appendLine("    file = ${str(s.cheatsFile)}")
        appendLine("    enabled_codes = ${arr(s.cheatsEnabledCodes)}")
        appendLine()
        appendLine("[library]")
        appendLine("    folders = ${arr(s.folders)}")
        appendLine("    recursive_folders = ${arr(s.recursiveFolders)}")
    }

    private fun str(v: String): String = "\"" + v.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
    private fun arr(v: List<String>): String = v.joinToString(prefix = "[", postfix = "]") { str(it) }

    // ---- parse ----

    private fun parse(text: String): Ps1Settings {
        var s = Ps1Settings()
        var section = ""
        for (raw in text.lineSequence()) {
            val line = stripComment(raw).trim()
            if (line.isEmpty()) continue
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.substring(1, line.length - 1).trim()
                continue
            }
            val eq = line.indexOf('=')
            if (eq < 0) continue
            val key = line.substring(0, eq).trim()
            val value = line.substring(eq + 1).trim()
            s = apply(s, section, key, value)
        }
        return s
    }

    private fun apply(s: Ps1Settings, section: String, key: String, value: String): Ps1Settings = when (section) {
        "bios" -> when (key) {
            "search_path" -> s.copy(biosSearchPath = unquote(value))
            "preferred_model" -> s.copy(preferredModel = unquote(value))
            "override_file" -> s.copy(biosOverrideFile = unquote(value))
            else -> s
        }
        "console" -> if (key == "region") s.copy(region = unquote(value)) else s
        "cpu" -> when (key) {
            "execution_mode" -> s.copy(cpuEngine = unquote(value))
            "fast_boot" -> s.copy(fastBoot = value.trim().equals("true", ignoreCase = true))
            else -> s
        }
        "runtime" -> when (key) {
            "display_scale" -> s.copy(displayScale = value.toIntOrNull() ?: s.displayScale)
            "logging_enabled" -> s.copy(loggingEnabled = value.toBoolean())
            "log_level" -> s.copy(logLevel = value.toIntOrNull() ?: s.logLevel)
            "quiet" -> s.copy(quiet = value.toBoolean())
            "frame_limit" -> s.copy(frameLimit = value.toBoolean())
            "speed_percent" -> s.copy(speedPercent = value.toIntOrNull() ?: s.speedPercent)
            "fps_limit" -> s.copy(fpsLimit = value.toIntOrNull() ?: s.fpsLimit)
            "fast_forward_speed" -> s.copy(fastForwardSpeed = value.toFloatOrNull() ?: s.fastForwardSpeed)
            // No coerceIn: -1 is the adaptive sentinel and the native side owns the -1..5 range.
            // Clamping against a stale local range here is how a new value gets silently eaten.
            "frame_skip" -> s.copy(frameSkip = value.toIntOrNull() ?: s.frameSkip)
            else -> s
        }
        "audio" -> when (key) {
            "volume" -> s.copy(audioVolume = value.toIntOrNull() ?: s.audioVolume)
            "fast_forward_volume" -> s.copy(audioFastForwardVolume = value.toIntOrNull() ?: s.audioFastForwardVolume)
            "muted" -> s.copy(audioMuted = value.toBoolean())
            "mute_fast_forward" -> s.copy(audioMuteFastForward = value.toBoolean())
            "swap_channels" -> s.copy(audioSwapChannels = value.toBoolean())
            "skip_reverb" -> s.copy(audioSkipReverb = value.toBoolean())
            "buffer_ms" -> s.copy(audioBufferMs = value.toIntOrNull() ?: s.audioBufferMs)
            "driver" -> s.copy(audioDriver = unquote(value))
            "background_playback" -> s.copy(audioBackgroundPlayback = value.toBoolean())
            else -> s
        }
        "paths" -> when (key) {
            "expansion_rom" -> s.copy(expansionRom = unquote(value))
            "default_psx_exe" -> s.copy(defaultPsxExe = unquote(value))
            else -> s
        }
        "video" -> when (key) {
            "vsync" -> s.copy(vsync = value.toBoolean())
            "gpu_backend" -> s.copy(gpuBackend = unquote(value))
            "texture_scale_mode" -> s.copy(textureScaleMode = value.toBoolean())
            "debug_panel" -> s.copy(debugPanel = value.toBoolean())
            "stretch_mode" -> s.copy(stretchMode = value.toBoolean())
            "display_aspect" -> s.copy(displayAspect = unquote(value))
            "display_aspect_custom" -> s.copy(displayAspectCustom = value.toFloatOrNull() ?: s.displayAspectCustom)
            "integer_scaling" -> s.copy(integerScaling = value.toBoolean())
            "wide_upscale" -> s.copy(wideUpscale = unquote(value))
            "renderer" -> s.copy(hwRasterizer = unquote(value) == "hardware")
            // No coerceIn here on purpose: the native side owns the 1..8 range, and clamping a
            // value against a stale local range is how a newly-added option gets eaten.
            "internal_scale" -> s.copy(internalScale = value.trim().toIntOrNull() ?: s.internalScale)
            "pgxp" -> s.copy(pgxp = value.trim().equals("true", ignoreCase = true))
            "accurate_mask_bit" -> s.copy(accurateMaskBit = value.toBoolean())
            "accurate_dither" -> s.copy(accurateDither = value.toBoolean())
            // A MISSING key keeps Ps1Settings()'s default, which is the documented
            // off/neutral value for every one of these — an existing on-device settings.toml
            // contains none of them.
            "widescreen_hack" -> s.copy(widescreenHack = value.toBoolean())
            "texture_filter" -> s.copy(textureFilter = unquote(value))
            // No coerceIn: the native side owns the range and clamps the request down to a
            // divisor of the internal scale. Clamping here against a stale local list is how
            // a newly-added value gets silently eaten.
            "downsample" -> s.copy(downsample = value.trim().toIntOrNull() ?: s.downsample)
            "deinterlace" -> s.copy(deinterlace = unquote(value))
            "overscan_crop" -> s.copy(overscanCrop = unquote(value))
            "display_rotation" -> s.copy(displayRotation = value.trim().toIntOrNull() ?: s.displayRotation)
            "texture_dump" -> s.copy(textureDump = value.toBoolean())
            "texture_replacements" -> s.copy(textureReplacements = value.toBoolean())
            "texture_dir" -> s.copy(textureDir = unquote(value))
            "line_detect" -> s.copy(lineDetect = unquote(value))
            else -> s
        }
        // A MISSING [input] section keeps Ps1Settings()'s default (analog ON) — which is what
        // we want for every settings.toml written before this key existed. Only an explicit
        // `false` turns it off.
        "input" -> when (key) {
            "analog_mode_default" -> s.copy(analogModeDefault = value.toBoolean())
            "multitap" -> s.copy(multitap = value.toBoolean())
            else -> s
        }
        // A MISSING [emulation] section keeps the Ps1Settings() defaults (rewind off,
        // runahead 0), which is what every settings.toml written before these keys existed
        // has. No coerceIn on the three numbers: psx/rewind.h owns their ranges and clamps
        // again, and clamping against a stale local list is how a new value gets eaten.
        "emulation" -> when (key) {
            "rewind" -> s.copy(rewind = value.toBoolean())
            "rewind_seconds" -> s.copy(rewindSeconds = value.toIntOrNull() ?: s.rewindSeconds)
            "rewind_frequency" -> s.copy(rewindFrequency = value.toIntOrNull() ?: s.rewindFrequency)
            "runahead" -> s.copy(runahead = value.toIntOrNull() ?: s.runahead)
            else -> s
        }
        // A MISSING [cheats] section keeps the Ps1Settings() defaults (off, no file, nothing
        // armed), which is what every settings.toml written before these keys existed has —
        // and is also the only safe reading of "this file says nothing about cheats".
        "cheats" -> when (key) {
            "enabled" -> s.copy(cheatsEnabled = value.toBoolean())
            "file" -> s.copy(cheatsFile = unquote(value))
            "enabled_codes" -> s.copy(cheatsEnabledCodes = parseArray(value))
            else -> s
        }
        "library" -> when (key) {
            "folders" -> s.copy(folders = parseArray(value))
            "recursive_folders" -> s.copy(recursiveFolders = parseArray(value))
            else -> s
        }
        else -> s
    }

    private fun stripComment(line: String): String {
        // Strip a `#` comment that is not inside a quoted string.
        var inStr = false
        for (i in line.indices) {
            val c = line[i]
            if (c == '"') inStr = !inStr
            else if (c == '#' && !inStr) return line.substring(0, i)
        }
        return line
    }

    private fun unquote(v: String): String {
        val t = v.trim()
        return if (t.length >= 2 && t.startsWith("\"") && t.endsWith("\"")) {
            t.substring(1, t.length - 1).replace("\\\"", "\"").replace("\\\\", "\\")
        } else t
    }

    /**
     * A TOML array of strings.
     *
     * Quote-aware, which it has to be: this used to split on every comma, so any element
     * CONTAINING one was torn into pieces. That was survivable while the only arrays were
     * folder paths; it is not survivable for `[cheats] enabled_codes`, where an entry called
     * "Infinite Health, Ammo And Keys" would be stored fine, read back as three names that
     * match no entry, and the cheat would simply stop working with the switch still on.
     */
    private fun parseArray(v: String): List<String> {
        val inner = v.trim().removePrefix("[").removeSuffix("]")
        val out = ArrayList<String>()
        val token = StringBuilder()
        var inStr = false
        var escaped = false
        for (c in inner) {
            when {
                escaped -> { token.append(c); escaped = false }
                inStr && c == '\\' -> { token.append(c); escaped = true }
                c == '"' -> { token.append(c); inStr = !inStr }
                !inStr && c == ',' -> { out.add(token.toString()); token.setLength(0) }
                else -> token.append(c)
            }
        }
        out.add(token.toString())
        return out.map { unquote(it.trim()) }.filter { it.isNotEmpty() }
    }

    private fun String.toBoolean(): Boolean = trim().equals("true", ignoreCase = true)
}
